name: CI

on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      - name: Setup NX Cloud
        run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="build"
        # Replace above command with the below one when e2e tests are available
        # run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm' # Cache node_modules

      - name: Install Dependencies
        run: npm ci

      - name: Set NX SHAs
        uses: nrwl/nx-set-shas@v4

      - if: ${{ github.event_name == 'pull_request' }}
        run: git branch --track main origin/main

      - name: Format
        run: npx nx-cloud record -- nx format:check

      - name: Lint, Build and Run Unit Tests
        run: npx nx affected --target=lint,test,build --parallel

      # Disabled e2e tests until available
      # - name: Lint, Build and Run Unit & E2E Tests
      #   run: npx nx affected --target=lint,test,build,e2e-ci --parallel
